site_name: Shor's Algorithm and Quantum Computing
nav:
- Home: index.md
- Shor's Algorithm: shors-algorithm.md
- Introduction to Quantum Computing: intro-quantum.md
- Quantum Fourier Transform: qft-qpe.md
- Quantum Shor's Algorithm: quantum-shors.md

theme: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
