site_name: Shor's Algorithm and Quantum Computing
nav:
- 1 - Introduction: index.md
- 2 - Shor's Algorithm: shors-algorithm.md
- 3 - Quantum Computing Preliminaries: intro-quantum.md
- 4 - Quantum Fourier Transform: qft.md
- 5 - Quantum Shor's Algorithm: quantum-shors.md
- 6 - Further reading: further.md
- 7 - References: bib.md

theme: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
